batch_size: 128
epochs: 200
lr_min: 0.0
lr_max: 0.1
weight_decay: 5e-4 
momentum: 0.9
seed: 0
out_dir: standard
dataset: cifar10
data_dir: ./cifar-data
wandb_key: 
lr_scheduler: multistep
opt_level: O2
loss_scale: "1.0"
model_name: resnet18
conv_layer: standard
activation: relu
groups: 1